pipeline {
    agent { dockerfile true }
    environment {
        EXAMPLE_CREDS = credentials('cred_vsrx_192_168_223_2')
    }
    stages {
        stage('Test') {
            when { changeset "firewall_policy_mgmt_pipeline/*"}
            steps {
                //$EXAMPLE_CREDS_USR
                //$EXAMPLE_CREDS_PSW
                //sh 'python3 deploy_to_network.py -username'
                sh 'python3 test_1.py -username $EXAMPLE_CREDS_USR -password $EXAMPLE_CREDS_PSW'
            }
        }
    }
}